// all hardcoded things are placed here
export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/";

export const ALL_REST = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=22.7532848&lng=75.8936962&offset=15&sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING";

export const REST_MENU = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=22.7532848&lng=75.8936962&restaurantId=";

export const restrauantList = [
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "69748",
                name: "Lootel Cafe-AICTSL",
                uuid: "a5f53f9d-6432-4acc-89c6-3ddda9382189",
                city: "18",
                area: "Navratan Bagh",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "hnqjdzvetfoda5pxzqgp",
                cuisines: ["Beverages"],
                tags: [],
                costForTwo: 25000,
                costForTwoString: "₹250 FOR TWO",
                deliveryTime: 42,
                minDeliveryTime: 42,
                maxDeliveryTime: 42,
                slaString: "42 MINS",
                lastMileTravel: 3.5,
                slugs: {
                    restaurant: "lootel-cafe-geeta-bhavan-south-tukoganj",
                    city: "indore",
                },
                cityState: "18",
                address: "AICTSL, Geeta Bhavan, Indore",
                locality: "Geeta Bhavan",
                parentId: 126009,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 3700,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "3.5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "69748",
                    deliveryTime: 42,
                    minDeliveryTime: 42,
                    maxDeliveryTime: 42,
                    lastMileTravel: 3.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.2",
                totalRatings: 100,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "218708",
                name: "Ambika Sweets",
                uuid: "71f2faa4-5119-47d5-b768-657ce1e4df3c",
                city: "18",
                area: "Manbhavan Nagar",
                totalRatingsString: "20+ ratings",
                cloudinaryImageId: "fj5mwferenzuvgnvelkq",
                cuisines: ["Indian", "Snacks", "Sweets", "Thalis"],
                tags: [],
                costForTwo: 25000,
                costForTwoString: "₹250 FOR TWO",
                deliveryTime: 43,
                minDeliveryTime: 43,
                maxDeliveryTime: 43,
                slaString: "43 MINS",
                lastMileTravel: 5.599999904632568,
                slugs: {
                    restaurant: "ambika-sweets-old-palasia-old-palasia",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "1, Bengali Colony, Near Shani Mandir, Kanadia Road, Old Palasia, Indore,Old Palasia,Indore",
                locality: "Old Palasia",
                parentId: 31332,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 5500,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 5500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "5500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "5.5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "218708",
                    deliveryTime: 43,
                    minDeliveryTime: 43,
                    maxDeliveryTime: 43,
                    lastMileTravel: 5.599999904632568,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.8",
                totalRatings: 20,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "68410",
                name: "Idli Hut",
                uuid: "769d69d5-d722-4c52-bbfb-c21912538396",
                city: "18",
                area: "Sapna Sangeeta Road",
                totalRatingsString: "1000+ ratings",
                cloudinaryImageId: "nnbeegfsgshvy9ncyovx",
                cuisines: ["South Indian", "Indian", "Beverages", "Chinese"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                slaString: "27 MINS",
                lastMileTravel: 3,
                slugs: {
                    restaurant: "idli-hut-sapna-sangeeta-bhawar-kuan",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "Ground Floor, Vatsalya Chambers, Sapna Sangeeta, Indore",
                locality: "Vatsalya Chambers",
                parentId: 105875,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                        {
                            meta: "30% off | Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "30% off up to ₹75 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "30% off up to ₹75 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 3700,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "3 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "68410",
                    deliveryTime: 27,
                    minDeliveryTime: 27,
                    maxDeliveryTime: 27,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.1",
                totalRatings: 1000,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "289932",
                name: "Madhuram Sweets",
                uuid: "0af37153-a888-487a-bd01-e665d82cbfa4",
                city: "18",
                area: "56 Dukan",
                totalRatingsString: "1000+ ratings",
                cloudinaryImageId: "dvrkcc5c3m3mq9jkzbsl",
                cuisines: ["Sweets", "Snacks"],
                tags: [],
                costForTwo: 15000,
                costForTwoString: "₹150 FOR TWO",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                slaString: "35 MINS",
                lastMileTravel: 3,
                slugs: {
                    restaurant: "madhuram-sweets-new-palasia-new-palasia-2",
                    city: "indore",
                },
                cityState: "18",
                address: "Madhuram sweets 21 to 27 shop, 56 shop, indore",
                locality: "New Palasia",
                parentId: 128676,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "20% off",
                    shortDescriptionList: [
                        {
                            meta: "20% off | Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "20% off up to ₹50 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "20% OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "20% off up to ₹50 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 3700,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "3 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "289932",
                    deliveryTime: 35,
                    minDeliveryTime: 35,
                    maxDeliveryTime: 35,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.5",
                totalRatings: 1000,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "93846",
                name: "Cake Boutique",
                uuid: "4254f4bc-5bcc-4bd5-a33a-ac018ddf485b",
                city: "18",
                area: "Sudama Nagar",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "ft96efkceqzq6dp29hgo",
                cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
                tags: [],
                costForTwo: 25000,
                costForTwoString: "₹250 FOR TWO",
                deliveryTime: 41,
                minDeliveryTime: 41,
                maxDeliveryTime: 41,
                slaString: "41 MINS",
                lastMileTravel: 4.199999809265137,
                slugs: {
                    restaurant:
                        "cake-boutique-sudama-nagar-sudama-nagar-rajendra-nagar",
                    city: "indore",
                },
                cityState: "18",
                address: "A/128, Sudama Nagar, Indore",
                locality: "Sector D",
                parentId: 11238,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "50% off",
                    shortDescriptionList: [
                        {
                            meta: "50% off | Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "50% off up to ₹100 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "50% OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "50% off up to ₹100 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 4500,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 4500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "4.1 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "93846",
                    deliveryTime: 41,
                    minDeliveryTime: 41,
                    maxDeliveryTime: 41,
                    lastMileTravel: 4.199999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.4",
                totalRatings: 500,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "96093",
                name: "shankar namkeen pratishthan",
                uuid: "df0c6437-cf41-40f0-87c6-ee6794c2c908",
                city: "18",
                area: "Sukhlia",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "ful5pmlj3dn8as9feg1t",
                cuisines: ["Desserts"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                slaString: "38 MINS",
                lastMileTravel: 4.5,
                slugs: {
                    restaurant: "shankar-namkeen-vijay-nagar-vijay-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "594/1 plot b mr-9 road electronic complex circle indore",
                locality: "Vijay Nagar",
                parentId: 181766,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "10% off",
                    shortDescriptionList: [
                        {
                            meta: "10% off | Use PARTY",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "10% off | Use code PARTY",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "10% OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use PARTY",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "10% off | Use code PARTY",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 4500,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 4500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 8:30 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "4.5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "96093",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 4.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.5",
                totalRatings: 500,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "579137",
                name: "The Baking Company",
                uuid: "796edea3-6931-4efb-91a2-d913a18610fd",
                city: "18",
                area: "Vijay Nagar",
                totalRatingsString: "20+ ratings",
                cloudinaryImageId: "ruwgo1vuejmg08nmvhnw",
                cuisines: ["Bakery"],
                tags: [],
                costForTwo: 39900,
                costForTwoString: "₹399 FOR TWO",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                slaString: "38 MINS",
                lastMileTravel: 3.700000047683716,
                slugs: {
                    restaurant: "cake-king-vijay-nagar-vijay-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "Plot no.196/3 nehru nagar gali no 3 indore, Indore, Indore, Indore, Madhya Pradesh - 452011",
                locality: "Nehru Nagar",
                parentId: 373865,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 3700,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 9 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "3.7 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "579137",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 3.700000047683716,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "1.8",
                totalRatings: 20,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "631842",
                name: "Seetavat Restaurant",
                uuid: "fddeaee8-c21f-4aec-ab6d-4ab3793c4a7e",
                city: "18",
                area: "Sarafa",
                totalRatingsString: "Too Few Ratings",
                cloudinaryImageId: "emfhevltdlt9y0rywq9l",
                cuisines: ["North Indian", "Chinese", "Indian"],
                tags: [],
                costForTwo: 30000,
                costForTwoString: "₹300 FOR TWO",
                deliveryTime: 42,
                minDeliveryTime: 42,
                maxDeliveryTime: 42,
                slaString: "42 MINS",
                lastMileTravel: 2.5,
                slugs: {
                    restaurant: "seetavat-restaurant-sarafa-sarafa",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "80, Nanda Nagar, Kushwah Nagar, Indore, Madhya Pradesh 452015, India",
                locality: "Nanda Nagar",
                parentId: 377969,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 2900,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 2900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2900",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 9 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "2.5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "631842",
                    deliveryTime: 42,
                    minDeliveryTime: 42,
                    maxDeliveryTime: 42,
                    lastMileTravel: 2.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "--",
                totalRatings: 0,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "263735",
                name: "Pure Veg Meals by Lunchbox",
                uuid: "e68951cb-8c3d-4d10-bfb4-d33dc6810fce",
                city: "18",
                area: "Sudama Nagar",
                totalRatingsString: "20+ ratings",
                cloudinaryImageId: "k5rppynokexzna1caaca",
                cuisines: ["North Indian", "Desserts", "Biryani"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 43,
                minDeliveryTime: 43,
                maxDeliveryTime: 43,
                slaString: "43 MINS",
                lastMileTravel: 5,
                slugs: {
                    restaurant:
                        "navratri-meals-by-faasos-sudama-nagar-sudama-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "First floor, Raghav regency, sec D, Sudama nagar, Above uco Bank, Near Lucky Bakery, INDORE  452009",
                locality: "Raghav Regency",
                parentId: 21938,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "FLAT125 off",
                    shortDescriptionList: [
                        {
                            meta: "FLAT125 off | Use FLATDEAL",
                            discountType: "Flat",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "FLAT125 off | Use FLATDEAL",
                            discountType: "Flat",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "₹125 OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use FLATDEAL",
                            discountType: "Flat",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "FLAT125 off | Use FLATDEAL",
                            discountType: "Flat",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "distance",
                            fee: 5500,
                            message: "",
                        },
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 5500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "5500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 9 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "263735",
                    deliveryTime: 43,
                    minDeliveryTime: 43,
                    maxDeliveryTime: 43,
                    lastMileTravel: 5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.9",
                totalRatings: 20,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "69746",
                name: "Arihant Dal Bati",
                uuid: "a4e79285-59f4-4acb-973b-2c1305b124b9",
                city: "18",
                area: "Jawahar Marg",
                totalRatingsString: "1000+ ratings",
                cloudinaryImageId: "qj3lqfftlidcltkh1lrr",
                cuisines: ["Thalis", "Rajasthani"],
                tags: [],
                costForTwo: 25000,
                costForTwoString: "₹250 FOR TWO",
                deliveryTime: 39,
                minDeliveryTime: 39,
                maxDeliveryTime: 39,
                slaString: "39 MINS",
                lastMileTravel: 1.5,
                slugs: {
                    restaurant: "arihant-dal-bati-rajwada-sarafa",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "9- Kalyan Palace, Hukumchand Marg, Opposite Kanch Mandir, Rajwada",
                locality: "Rajwada",
                parentId: 35861,
                unserviceable: true,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                aggregatedDiscountInfo: {
                    header: "10% off",
                    shortDescriptionList: [
                        {
                            meta: "10% off | Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "10% off up to ₹40 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                aggregatedDiscountInfoV2: {
                    header: "10% OFF",
                    shortDescriptionList: [
                        {
                            meta: "Use TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    descriptionList: [
                        {
                            meta: "10% off up to ₹40 | Use code TRYNEW",
                            discountType: "Percentage",
                            operationType: "RESTAURANT",
                        },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                },
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 2900,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 2900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2900",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "1.5 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "69746",
                    deliveryTime: 39,
                    minDeliveryTime: 39,
                    maxDeliveryTime: 39,
                    lastMileTravel: 1.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.9",
                totalRatings: 1000,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "137642",
                name: "Desserts By Pihu",
                uuid: "64ceb9eb-f2e6-4c54-aef4-1e452842abd9",
                city: "18",
                area: "Vijaynagar",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "wehyjpe0kfhcuumspccb",
                cuisines: ["Desserts"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 34,
                minDeliveryTime: 34,
                maxDeliveryTime: 34,
                slaString: "34 MINS",
                lastMileTravel: 6.300000190734863,
                slugs: {
                    restaurant: "desserts-by-pihu-vijay-nagar-vijay-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "khushi FH-311 scheme number 54,vijaynagar indore (mp)452010",
                locality: "5th Scheme",
                parentId: 71464,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "distance",
                            fee: 6500,
                            message: "",
                        },
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 6500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "6.3 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "137642",
                    deliveryTime: 34,
                    minDeliveryTime: 34,
                    maxDeliveryTime: 34,
                    lastMileTravel: 6.300000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.7",
                totalRatings: 500,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "431389",
                name: "LALIT KE NAMKEEN",
                uuid: "09478aba-99ff-4e6f-9d10-1568a1626333",
                city: "18",
                area: "Vijay Nagar",
                totalRatingsString: "Too Few Ratings",
                cloudinaryImageId: "nzw23fklhtx1hwpq2pnx",
                cuisines: ["Snacks"],
                tags: [],
                costForTwo: 30000,
                costForTwoString: "₹300 FOR TWO",
                deliveryTime: 45,
                minDeliveryTime: 45,
                maxDeliveryTime: 45,
                slaString: "45 MINS",
                lastMileTravel: 6.099999904632568,
                slugs: {
                    restaurant: "lalit-ke-namkeen-vijay-nagar-vijay-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "36 B-F 1/2, Padmavati Avenue Scheme No.54, Opp. Sica School Indore 452002",
                locality: "54 Scheme",
                parentId: 261491,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 6500,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 6500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "6 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "431389",
                    deliveryTime: 45,
                    minDeliveryTime: 45,
                    maxDeliveryTime: 45,
                    lastMileTravel: 6.099999904632568,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "--",
                totalRatings: 0,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
    {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
            type: "restaurant",
            data: {
                type: "F",
                id: "660385",
                name: "Tanu's Kitchen",
                uuid: "56f5858e-49dd-4053-8e58-c2425752d1f0",
                city: "18",
                area: "Vijay Nagar",
                totalRatingsString: "Too Few Ratings",
                cloudinaryImageId: "dbddc2d34b706d29dee070266050affc",
                cuisines: ["Fast Food", "Pizzas", "Chinese"],
                tags: [],
                costForTwo: 30000,
                costForTwoString: "₹300 FOR TWO",
                deliveryTime: 47,
                minDeliveryTime: 47,
                maxDeliveryTime: 47,
                slaString: "47 MINS",
                lastMileTravel: 6.800000190734863,
                slugs: {
                    restaurant: "tanu's-kitchen-vijay-nagar-vijay-nagar",
                    city: "indore",
                },
                cityState: "18",
                address:
                    "SHOP NO.8 ARANY NAGAR, SCHEME  NO.78 VIJAY NAGAR, Indore, Indore,  Indore, Madhya Pradesh - 452001",
                locality: "Arany nagar",
                parentId: 201083,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                    fees: [
                        {
                            name: "time",
                            fee: 0,
                            message: "",
                        },
                        {
                            name: "distance",
                            fee: 6500,
                            message: "",
                        },
                        {
                            name: "special",
                            fee: 0,
                            message: "",
                        },
                    ],
                    totalFees: 6500,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6500",
                    icon: "",
                },
                availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10 am, today",
                    nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                },
                lastMileTravelString: "6.8 kms",
                hasSurge: false,
                sla: {
                    restaurantId: "660385",
                    deliveryTime: 47,
                    minDeliveryTime: 47,
                    maxDeliveryTime: 47,
                    lastMileTravel: 6.800000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "--",
                totalRatings: 0,
                new: false,
            },
            subtype: "basic",
        },
        parentWidget: false,
    },
];
